name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Set BrowserStack Credentials
          run: |
            echo "BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
            echo "BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
        - name: Test
          run: npm run bstack-single
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
